import Head from "next/head";
import Image from "next/image";
import {
  AppShell,
  Grid,
  Group,
  Stack,
  Title,
  Text,
  Container,
  Input,
} from "@mantine/core";
import Sidebar from "../components/Sidebar";
import { Search } from "tabler-icons-react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell padding={0} navbar={<Sidebar />} p={0}>
        <Grid ml={260} gutter={0}>
          <Grid.Col span={4} bg={"#f8f8f8"} h={"100vh"} p={30}>
            <Stack>
              <Title order={1}>Dashboard</Title>
              <Stack>
                {[
                  {
                    name: "Connections",
                    val: 2632,
                    growth: "56%",
                  },
                  {
                    name: "Followers",
                    val: 2667,
                    growth: "0%",
                  },
                  {
                    name: "Connect Invites",
                    val: 100,
                    growth: "60%",
                  },
                ].map((item, index) => (
                  <Container key={index}>
                    <Title order={3}>{item.name}</Title>
                    <Group>
                      <Text>{item.val}</Text>
                      <Text>{item.growth}</Text>
                    </Group>
                  </Container>
                ))}
              </Stack>

              <Image src="/graph.svg" width={400} height={300} alt="graph" />
            </Stack>
          </Grid.Col>
          <Grid.Col span={8} p={30}>
            <Input
              w={300}
              radius={"8px"}
              variant="filled"
              placeholder="Search"
              rightSection={
                <Search
                  size="1rem"
                  style={{ display: "block", opacity: 0.5 }}
                />
              }
            />

            <Stack>
              <Title order={2}>Campigns Activity</Title>
              <Group>
                {[
                  {
                    name: "Invitations Sent",
                    val: "286",
                  },
                  {
                    name: "Pending Invitations",
                    val: "12",
                  },
                  {
                    name: "Profile Views",
                    val: "2891",
                  },
                ].map((item, index) => (
                  <Stack key={index}>
                    <Text>{item.name}</Text>
                    <Text>{item.val}</Text>
                  </Stack>
                ))}
              </Group>
              <Image src="/graph2.png" width={600} height={270} alt="graph" />
            </Stack>

            <Stack>
              <Title order={2}>Recent Activity</Title>
              
            </Stack>
          </Grid.Col>
        </Grid>
      </AppShell>
    </>
  );
}
