import Head from "next/head";
import Image from "next/image";
import {
  AppShell,
  Grid,
  Group,
  Stack,
  Title,
  Text,
  Container,
  Input,
  Badge,
  Button,
  Avatar,
} from "@mantine/core";
import Sidebar from "../components/Sidebar";
import { Bell, Notification, Search, TrendingUp } from "tabler-icons-react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell padding={0} navbar={<Sidebar />} p={0}>
        <Grid ml={260} gutter={0}>
          <Grid.Col span={4} bg={"#f8f8f8"} h={"100vh"} p={30}>
            <Stack>
              <Title order={1}>Dashboard</Title>
              <Stack my={60} align="stretch">
                {[
                  {
                    name: "Connections",
                    val: 2632,
                    growth: "56%",
                  },
                  {
                    name: "Followers",
                    val: 2667,
                    growth: "0%",
                  },
                  {
                    name: "Connect Invites",
                    val: 100,
                    growth: "60%",
                  },
                ].map((item, index) => (
                  <Container key={index} w="100%">
                    <Title order={4} color="#94979A">
                      {item.name}
                    </Title>
                    <Group position="apart">
                      <Text size={"28px"} ff="sans-serif">
                        {item.val}
                      </Text>
                      <Badge color="teal" size="lg">
                        <TrendingUp size={"10px"} /> &nbsp;
                        {item.growth}
                      </Badge>
                    </Group>
                  </Container>
                ))}
              </Stack>

              <Image src="/graph.svg" width={400} height={300} alt="graph" />
            </Stack>
          </Grid.Col>
          <Grid.Col span={8} p={30}>
            <Group position="apart">
              <Input
                w={300}
                radius={"8px"}
                variant="filled"
                placeholder="Search"
                rightSection={
                  <Search
                    size="1rem"
                    style={{ display: "block", opacity: 0.5 }}
                  />
                }
              />

              <Group>
                <Button bg={"#f8f8f8"} radius="28px">
                  <Bell color="#000" />
                </Button>

                <Avatar radius={"xl"} />
                <Text size={"lg"}>Jacob Frost</Text>
              </Group>
            </Group>

            <Stack mt={80} mb={40}>
              <Group position="apart">
                <Title order={2}>Campigns Analytics</Title>
                <Badge color="gray" size="lg">
                  Mar 10 - Apr 10
                </Badge>
              </Group>
              <Group mt={20}>
                {[
                  {
                    name: "Invitations Sent",
                    val: "286",
                  },
                  {
                    name: "Pending Invitations",
                    val: "12",
                  },
                  {
                    name: "Profile Views",
                    val: "2891",
                  },
                ].map((item, index) => (
                  <Stack key={index} spacing="0">
                    <Text color="#94979A">{item.name}</Text>
                    <Text size={"28px"} ff="sans-serif">
                      {item.val}
                    </Text>
                  </Stack>
                ))}
              </Group>
              <Image src="/graph2.png" width={800} height={370} alt="graph" />
            </Stack>

            <Stack>
              <Title order={2}>Recent Activity</Title>

              <Stack align={"flex-start"}>
                <Group>
                  <Avatar radius={"xl"} />
                  <Text size={"lg"}>Alex Morgan sent you a message.</Text>
                </Group>
              </Stack>
            </Stack>
          </Grid.Col>
        </Grid>
      </AppShell>
    </>
  );
}
